import type { AdvancedSettingsPageState } from "#templates/admin/settings-advanced.tsx";

export const advancedDefaultState: AdvancedSettingsPageState = {
  addressLookupApiKeyConfigured: false,
  addressLookupProvider: "none",
  adminTemplates: { html: "", subject: "", text: "" },
  appleWalletConfigured: false,
  appleWalletPassTypeId: "",
  appleWalletTeamId: "",
  attendeeColumnOrder: "",
  bunnyCdnEnabled: false,
  bunnyDnsEnabled: false,
  bunnyDnsSubdomainSuffix: "",
  bunnySubdomain: "",
  businessEmail: "",
  cdnHostname: "",
  confirmationTemplates: { html: "", subject: "", text: "" },
  customCss: "",
  customDomain: "",
  customDomainLastValidated: "",
  emailApiKeyConfigured: false,
  emailFromAddress: "",
  emailProvider: "",
  existingPaymentProvider: null,
  externalOrderEnabled: false,
  googleWalletConfigured: false,
  googleWalletIssuerId: "",
  googleWalletServiceAccountEmail: "",
  hostAppleWalletLabel: "",
  hostEmailLabel: "",
  hostGoogleWalletLabel: "",
  listingColumnOrder: "",
  scheduledTaskKey: "",
  showPublicApi: false,
  smsGatewayBaseUrl: "",
  smsGatewayPassphraseConfigured: false,
  smsGatewayPasswordConfigured: false,
  smsGatewayUsername: "",
  smsGatewayWebhookConfigured: false,
  subdomainPreview: "",
  subdomainPreviewFullDomain: "",
  theme: "light",
};
