import { operation, route } from "#shared/admin-surface/definitions.ts";

export const routes = [
  route(
    "deleteAttendeesByAttendeeIdDelete",
    "attendees",
    "DELETE",
    "/admin/attendees/:attendeeId/delete",
  ),
  route("getAttendees", "attendees", "GET", "/admin/attendees"),
  route(
    "getAttendeesByAttendeeId",
    "attendees",
    "GET",
    "/admin/attendees/:attendeeId",
  ),
  route(
    "getAttendeesByAttendeeIdByTab",
    "attendees",
    "GET",
    "/admin/attendees/:attendeeId/:tab",
  ),
  route(
    "getAttendeesByAttendeeIdDelete",
    "attendees",
    "GET",
    "/admin/attendees/:attendeeId/delete",
  ),
  route(
    "getAttendeesByAttendeeIdResendNotification",
    "attendees",
    "GET",
    "/admin/attendees/:attendeeId/resend-notification",
  ),
  route("getAttendeesCsv", "attendees", "GET", "/admin/attendees/csv"),
  route("getAttendeesNew", "attendees", "GET", "/admin/attendees/new"),
  route(
    "postAttendeesByAttendeeId",
    "attendees",
    "POST",
    "/admin/attendees/:attendeeId",
  ),
  route(
    "postAttendeesByAttendeeIdDelete",
    "attendees",
    "POST",
    "/admin/attendees/:attendeeId/delete",
  ),
  route(
    "postAttendeesByAttendeeIdLogistics",
    "attendees",
    "POST",
    "/admin/attendees/:attendeeId/logistics",
  ),
  route(
    "postAttendeesByAttendeeIdMerge",
    "attendees",
    "POST",
    "/admin/attendees/:attendeeId/merge",
  ),
  operation(
    "postAttendeesByAttendeeIdRefreshPayment",
    "attendees",
    "/admin/attendees/:attendeeId/refresh-payment",
  ),
  route(
    "postAttendeesByAttendeeIdResendNotification",
    "attendees",
    "POST",
    "/admin/attendees/:attendeeId/resend-notification",
  ),
  route("postAttendeesNew", "attendees", "POST", "/admin/attendees/new"),
  route(
    "postListingByListingIdAttendee",
    "attendees",
    "POST",
    "/admin/listing/:listingId/attendee",
  ),
  operation(
    "postListingByListingIdAttendeeByAttendeeIdCheckin",
    "attendees",
    "/admin/listing/:listingId/attendee/:attendeeId/checkin",
  ),
  route(
    "postListingByListingIdAttendeeByAttendeeIdDeleteIncomplete",
    "attendees",
    "POST",
    "/admin/listing/:listingId/attendee/:attendeeId/delete-incomplete",
  ),
] as const;
