import { route } from "#shared/admin-surface/definitions.ts";

export const routes = [
  route(
    "getSettingsStatuses",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses",
  ),
  route(
    "getSettingsStatusesByIdDelete",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/:id/delete",
  ),
  route(
    "getSettingsStatusesByIdEdit",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/:id/edit",
  ),
  route(
    "getSettingsStatusesNew",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/new",
  ),
  route(
    "postSettingsStatuses",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses",
  ),
  route(
    "postSettingsStatusesByIdDelete",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/delete",
  ),
  route(
    "postSettingsStatusesByIdEdit",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/edit",
  ),
  route(
    "postSettingsStatusesByIdMoveDown",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/move-down",
  ),
  route(
    "postSettingsStatusesByIdMoveUp",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/move-up",
  ),
] as const;
