import { moveRoutes, route } from "#shared/admin-surface/definitions.ts";

export const routes = [
  route(
    "getSettingsStatuses",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses",
  ),
  route(
    "getSettingsStatusesByIdDelete",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/:id/delete",
  ),
  route(
    "getSettingsStatusesNew",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/new",
  ),
  route(
    "postSettingsStatuses",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses",
  ),
  route(
    "postSettingsStatusesByIdDelete",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/delete",
  ),
  route(
    "postSettingsStatusesByIdEdit",
    "settingsStatuses",
    "POST",
    "/admin/settings/statuses/:id/edit",
  ),
  ...moveRoutes(
    "postSettingsStatusesById",
    "settingsStatuses",
    "/admin/settings/statuses/:id",
  ),
  route(
    "getSettingsStatusesById",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/:id",
  ),
  route(
    "getSettingsStatusesByIdByTab",
    "settingsStatuses",
    "GET",
    "/admin/settings/statuses/:id/:tab",
  ),
] as const;
