services:
  - type: web
    name: chobble-tickets
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_TOKEN
        sync: false
      - key: DB_ENCRYPTION_KEY
        sync: false
      - key: ADMIN_EMAIL_ADDRESS
        sync: false
      - key: PORT
        value: "3000"
