import { decode } from "@jridgewell/sourcemap-codec";
import { utf8ByteLength } from "#src/shared/bytes.ts";

export interface BundleSourceMap {
  mappings: string;
  sources: string[];
  sourcesContent?: Array<string | null>;
}

export interface SourceBytes {
  bytes: number;
  source: string;
}

export interface BundleAttribution {
  bySource: SourceBytes[];
  bySourceLine: ReadonlyMap<string, number>;
  totalBytes: number;
}

export type BundleCategory =
  | "Application source"
  | "Inlined browser/static module"
  | "Inlined WASM"
  | "JSR dependencies"
  | "npm dependencies"
  | "Build glue and generated code";

export const sortSourceBytes = (
  sources: readonly SourceBytes[],
): SourceBytes[] => sources.toSorted((left, right) => right.bytes - left.bytes);

const sourceBytesFromTotals = (
  totals: ReadonlyMap<string, number>,
): SourceBytes[] =>
  sortSourceBytes(
    [...totals.entries()].map(([source, bytes]) => ({ bytes, source })),
  );

const addBytes = (
  totals: Map<string, number>,
  key: string,
  bytes: number,
): void => {
  if (bytes === 0) return;
  const current = totals.get(key);
  totals.set(key, current === undefined ? bytes : current + bytes);
};

type MappingLines = ReturnType<typeof decode>;
type MappingLine = MappingLines[number];
type MappingSegment = MappingLine[number];
type MappedSegment = Exclude<MappingSegment, [number]>;

interface AttributionTotals {
  bySource: Map<string, number>;
  bySourceLine: Map<string, number>;
}

export const sourceLineKey = (source: string, line: number): string =>
  `${source}\0${line}`;

const isMappedSegment = (segment: MappingSegment): segment is MappedSegment =>
  segment[1] !== undefined;

const attributeSegment = (
  totals: AttributionTotals,
  map: BundleSourceMap,
  line: string,
  segment: MappingSegment,
  endColumn: number,
): void => {
  const bytes = utf8ByteLength(line.slice(segment[0], endColumn));
  if (!isMappedSegment(segment)) {
    addBytes(totals.bySource, "[unmapped]", bytes);
    return;
  }
  const sourceIndex = segment[1];
  const originalLine = segment[2];
  const source = map.sources[sourceIndex];
  if (source === undefined) {
    throw new Error(`Missing source-map source ${sourceIndex}`);
  }
  addBytes(totals.bySource, source, bytes);
  addBytes(totals.bySourceLine, sourceLineKey(source, originalLine), bytes);
};

const attributeLine = (
  totals: AttributionTotals,
  map: BundleSourceMap,
  line: string,
  segments: MappingLine,
): void => {
  const first = segments[0];
  if (first === undefined) {
    addBytes(totals.bySource, "[unmapped]", utf8ByteLength(line));
    return;
  }
  addBytes(
    totals.bySource,
    "[unmapped]",
    utf8ByteLength(line.slice(0, first[0])),
  );
  for (const [index, segment] of segments.entries()) {
    const next = segments[index + 1];
    attributeSegment(
      totals,
      map,
      line,
      segment,
      next === undefined ? line.length : next[0],
    );
  }
};

/** Attribute each generated byte to the source-map segment that produced it. */
export const attributeGeneratedBytes = (
  code: string,
  map: BundleSourceMap,
): BundleAttribution => {
  const totals: AttributionTotals = {
    bySource: new Map(),
    bySourceLine: new Map(),
  };
  const codeLines = code.split("\n");
  const mappingLines = decode(map.mappings);

  for (const [lineNumber, line] of codeLines.entries()) {
    const segments = mappingLines[lineNumber];
    attributeLine(totals, map, line, segments === undefined ? [] : segments);
    if (lineNumber < codeLines.length - 1) {
      addBytes(totals.bySource, "[unmapped]", 1);
    }
  }

  return {
    bySource: sourceBytesFromTotals(totals.bySource),
    bySourceLine: totals.bySourceLine,
    totalBytes: utf8ByteLength(code),
  };
};

export const categoryForSource = (source: string): BundleCategory => {
  if (source.startsWith("inline-jsquash-wasm:")) return "Inlined WASM";
  if (source.startsWith("inline-assets:")) {
    return "Inlined browser/static module";
  }
  if (source.startsWith("../src/")) return "Application source";
  if (source.startsWith("https://jsr.io/")) return "JSR dependencies";
  if (source.includes("/node_modules/")) return "npm dependencies";
  return "Build glue and generated code";
};

export const dependencyName = (source: string): string | null => {
  const npmMatch = /\/node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(source);
  if (npmMatch?.[1]) return npmMatch[1];
  if (!source.startsWith("https://jsr.io/")) return null;
  const [scope, name] = new URL(source).pathname.split("/").filter(Boolean);
  return scope && name ? `${scope}/${name}` : null;
};

const APPLICATION_AREAS: ReadonlyArray<readonly [string, string]> = [
  ["/shared/db/migrations", "Database migrations"],
  ["/locales/", "Locales"],
  ["/ui/templates/admin/", "Admin templates"],
  ["/features/admin/", "Admin routes"],
  ["/ui/templates/public/", "Public templates"],
  ["/features/public/", "Public routes"],
  ["/features/api/", "API routes and webhooks"],
  ["/shared/db/", "Shared database code"],
  ["/ui/templates/", "Shared UI templates"],
  ["/shared/", "Shared domain and runtime"],
  ["/features/", "Other features and routing"],
];

export const applicationArea = (source: string): string | null => {
  if (!source.startsWith("../src/")) return null;
  const found = APPLICATION_AREAS.find(([part]) => source.includes(part));
  return found === undefined ? "Entry and root modules" : found[1];
};

export const groupSourceBytes = (
  sources: readonly SourceBytes[],
  nameFrom: (source: string) => string | null,
): SourceBytes[] => {
  const totals = new Map<string, number>();
  for (const item of sources) {
    const name = nameFrom(item.source);
    if (typeof name === "string") addBytes(totals, name, item.bytes);
  }
  return sourceBytesFromTotals(totals);
};
