/**
 * The syntax words the lexer keeps as themselves: JavaScript's and
 * TypeScript's reserved words, plus its literal words. A rename never touches
 * one, so `typescript-lex` keeps these words while every chosen name is
 * masked to one symbol.
 */

/** Sorted alphabetically; keep it that way. */
export const SYNTAX_WORDS = new Set([
  "abstract",
  "accessor",
  "as",
  "async",
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "declare",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "from",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "infer",
  "instanceof",
  "interface",
  "is",
  "keyof",
  "let",
  "module",
  "namespace",
  "new",
  "null",
  "of",
  "out",
  "override",
  "private",
  "protected",
  "public",
  "readonly",
  "return",
  "satisfies",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "type",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);
