/**
 * Group test files into generated entry modules so many files share one
 * isolate.
 *
 * `deno test` runs every test file in its own isolate, and each isolate
 * re-evaluates the whole app module graph — several hundred milliseconds of
 * CPU per file, times ~940 files per full run. A group entry file simply
 * imports a shard of test files, so all of them register their tests into one
 * isolate and the module graph is evaluated once per group instead. The
 * focused runner (`deno task test:files`) never groups — you always get the
 * exact files you asked for, each in its own isolate.
 *
 * Files with global (module-level) BDD hooks cannot be merged: with
 * @std/testing/bdd a module-level `beforeEach(...)` applies to the whole
 * module, and registering a global hook after another module's tests is an
 * error. Those files run as their own entries, exactly as before. The same
 * escape is available to any file that genuinely needs its own isolate: give
 * it a module-level `// test-groups: run-alone` comment.
 */

import { join, relative } from "node:path";
import { collectFiles } from "./walk-files.ts";

/** Where the generated group entry files live, relative to the project root.
 * Outside test/ so tree-walking checks (code quality, i18n coverage) never see
 * them, and gitignored. */
export const GROUPS_DIR = ".test-groups";

/** Marker a test file can carry to opt out of isolate sharing. */
export const RUN_ALONE_MARKER = "test-groups: run-alone";

// A hook call at column 0 is a *global* BDD hook (inside a describe it is
// always indented — Biome enforces the formatting).
const GLOBAL_HOOK_RE = /^(?:beforeAll|beforeEach|afterAll|afterEach)\(/m;

/** True when a test file must run in its own isolate instead of a group. */
export const mustRunAlone = (source: string): boolean =>
  GLOBAL_HOOK_RE.test(source) || source.includes(RUN_ALONE_MARKER);

/** Deal `items` round-robin into `groupCount` piles (sorted input stays
 * spread across piles, so no pile ends up with one directory's heavy files). */
export const shardRoundRobin = <T>(items: T[], groupCount: number): T[][] => {
  const count = Math.max(1, Math.min(groupCount, items.length));
  const piles: T[][] = Array.from({ length: count }, () => []);
  items.forEach((item, index) => {
    piles[index % count]!.push(item);
  });
  return piles;
};

/** The source of one generated group entry: an import per member file. */
export const renderGroupEntry = (importPaths: string[]): string =>
  `// Generated by scripts/test-groups.ts — do not edit, do not commit.\n${importPaths
    .map((path) => `import "${path}";`)
    .join("\n")}\n`;

export type TestGroupPlan = {
  /** Shards of files that share an isolate via a generated entry. */
  grouped: string[][];
  /** Files that keep their own isolate (global hooks or run-alone marker). */
  solo: string[];
};

/** Split test files into isolate-sharing shards and solo files. Pure. */
export const planTestGroups = (
  files: { path: string; runsAlone: boolean }[],
  groupCount: number,
): TestGroupPlan => {
  const groupable = files.filter((file) => !file.runsAlone);
  return {
    grouped: shardRoundRobin(
      groupable.map((file) => file.path),
      groupCount,
    ),
    solo: files.filter((file) => file.runsAlone).map((file) => file.path),
  };
};

/** Every test file under `root`/test, sorted for determinism. Throws if a
 * shared helper (a non-test .ts file) registers global hooks: its importers
 * look groupable but would blow up the whole group at load, so the helper
 * must expose a setup function the test files call from their own suites. */
export const collectTestFiles = async (root: string): Promise<string[]> => {
  const allTs = await collectFiles(join(root, "test"), (path) =>
    path.endsWith(".ts"),
  );
  for (const helper of allTs.filter((path) => !path.endsWith(".test.ts"))) {
    if (GLOBAL_HOOK_RE.test(await Deno.readTextFile(helper))) {
      throw new Error(
        `${helper} is a shared test helper but registers a global BDD hook — ` +
          "export a setup function and call it from each test file's own suite instead",
      );
    }
  }
  return allTs.filter((path) => path.endsWith(".test.ts"));
};

/**
 * How many groups to shard into: a few per test worker, so `--parallel`
 * (which runs one entry per worker at a time) always has entries queued and
 * an unlucky heavy shard cannot dominate the tail.
 */
export const defaultGroupCount = (workers: number): number =>
  Math.max(8, workers * 4);

const testWorkerCount = (): number => {
  const jobs = Number.parseInt(Deno.env.get("DENO_JOBS") ?? "", 10);
  return Number.isFinite(jobs) && jobs > 0
    ? jobs
    : navigator.hardwareConcurrency;
};

export type WrittenTestGroups = {
  /** Paths to hand to `deno test`: group entries plus solo files. */
  runArgs: string[];
  /** The real test files, for the progress bar's test-count estimate. */
  testFiles: string[];
  /** Remove the generated entries. */
  cleanup: () => Promise<void>;
};

/**
 * Plan and write the group entry files for a full-suite run. Entries import
 * their members with paths relative to GROUPS_DIR, so the project's import
 * map applies unchanged.
 */
export const writeTestGroups = async (
  root: string,
  groupCount: number = defaultGroupCount(testWorkerCount()),
): Promise<WrittenTestGroups> => {
  const paths = await collectTestFiles(root);
  const files = await Promise.all(
    paths.map(async (path) => ({
      path,
      runsAlone: mustRunAlone(await Deno.readTextFile(path)),
    })),
  );
  const plan = planTestGroups(files, groupCount);

  const groupsDir = join(root, GROUPS_DIR);
  await Deno.mkdir(groupsDir, { recursive: true });
  const groupPaths: string[] = [];
  for (const [index, members] of plan.grouped.entries()) {
    const groupPath = join(groupsDir, `group-${index}.test.ts`);
    await Deno.writeTextFile(
      groupPath,
      renderGroupEntry(members.map((member) => `../${relative(root, member)}`)),
    );
    groupPaths.push(groupPath);
  }

  return {
    cleanup: async () => {
      for (const groupPath of groupPaths) {
        await Deno.remove(groupPath).catch(() => {
          // already gone — nothing left to clean up
        });
      }
      await Deno.remove(groupsDir).catch(() => {
        // not empty or already gone — leave it for the next run to reuse
      });
    },
    runArgs: [...groupPaths, ...plan.solo],
    testFiles: paths,
  };
};
