/**
 * Admin holiday management page templates.
 *
 * The four standard pages (list / new / edit / delete) are generated by
 * {@link defineAdminResourcePages} from one config so the path, title,
 * table-column, form-field, and delete-confirmation conventions live in one
 * place. {@link HolidayTable} stays as a standalone export because the
 * dashboard renders it outside the resource list shell.
 */

import { t } from "#i18n";
import { entityToFieldValues, renderFields } from "#shared/forms.tsx";
import { escapeHtml, Raw } from "#shared/jsx/jsx-runtime.ts";
import type { AdminSession, Holiday } from "#shared/types.ts";
import { defineAdminResourcePages } from "#templates/admin/resource-pages.tsx";
import { ActionButton, GuideLink } from "#templates/components/actions.tsx";
import {
  type DataColumn,
  dataTable,
} from "#templates/components/data-table.tsx";
import { getHolidayFields } from "#templates/fields.ts";

/** Columns for the holidays table — declared once so the header order and
 *  cell order can't drift apart. */
const holidayColumns: DataColumn<Holiday>[] = [
  {
    cell: (holiday) => (
      <a href={`/admin/holidays/${holiday.id}/edit`}>{holiday.name}</a>
    ),
    header: t("common.name"),
  },
  { cell: (h) => h.start_date, header: t("holidays.col.start_date") },
  { cell: (h) => h.end_date, header: t("holidays.col.end_date") },
];

/** Shared holidays table used by the holiday settings page and dashboard. */
export const HolidayTable = ({
  holidays,
  scrollClass,
}: {
  holidays: Holiday[];
  scrollClass: string;
}): string => String(dataTable(holidayColumns)(holidays, { scrollClass }));

/** Holiday create/edit form values. Kept as a public export because the
 *  demo/replay harness and tests read it directly. */
export const holidayToFieldValues = (
  holiday?: Holiday,
): Record<string, string | number | null> =>
  entityToFieldValues(holiday, getHolidayFields(), {});

const { deletePage, editPage, listPage, newPage } =
  defineAdminResourcePages<Holiday>({
    active: "/admin/settings",
    basePath: "/admin/holidays",
    delete: {
      confirm: (holiday) => ({
        args: {
          end: holiday.end_date,
          name: escapeHtml(holiday.name),
          start: holiday.start_date,
        },
        key: "holidays.delete.confirm",
      }),
      danger: false,
      heading: t("holidays.delete.heading"),
      label: t("holidays.delete.confirm_label"),
      name: (holiday) => holiday.name,
      prompt: (holiday) => ({
        args: { name: holiday.name },
        key: "holidays.delete.confirm_prompt",
      }),
    },
    labels: {
      addHeading: t("holidays.add.heading"),
      addSubmit: t("holidays.add.submit"),
      addTitle: t("holidays.add.title"),
      deleteButton: t("holidays.delete.submit"),
      deleteLabel: t("holidays.delete.confirm_label"),
      deleteTitle: t("holidays.delete.heading"),
      editHeading: t("holidays.edit.heading"),
      editTitle: t("holidays.edit.title"),
      listTitle: t("terms.holidays"),
    },
    list: {
      actions: (
        <>
          <ActionButton href="/admin/holidays/new" icon="plus">
            {t("holidays.add_holiday")}
          </ActionButton>
          <GuideLink href="/admin/guide#holidays">
            {t("holidays.guide_link")}
          </GuideLink>
        </>
      ),
      columns: holidayColumns,
      empty: <p>{t("holidays.no_holidays")}</p>,
    },
    renderFields: (holiday) => (
      <Raw
        html={renderFields(
          getHolidayFields(),
          holiday ? holidayToFieldValues(holiday) : {},
        )}
      />
    ),
  });

/** Admin holidays list page. */
export const adminHolidaysPage = (
  holidays: Holiday[],
  session: AdminSession,
  successMessage?: string,
): string => listPage(holidays, session, undefined, successMessage);

/** Admin holiday create page. */
export const adminHolidayNewPage = newPage;

/** Admin holiday edit page. */
export const adminHolidayEditPage = editPage;

/** Admin holiday delete confirmation page. */
export const adminHolidayDeletePage = deletePage;
