/**
 * Admin holiday management page templates.
 *
 * The list, new, and delete pages are generated by
 * {@link defineAdminResourcePages}. The edit form is a panel in the holiday
 * entity page. {@link HolidayTable} stays as a standalone export because the
 * dashboard renders it outside the resource list shell.
 */

/* jscpd:ignore-start */
import { t } from "#i18n";
import { adminPath, adminPattern } from "#shared/admin-surface.ts";
import type { FormRenderValuesFor } from "#shared/forms/definition.ts";
import { entityToFieldValues } from "#shared/forms/values.ts";
import { escapeHtml } from "#shared/jsx/escape-html.ts";
import { Raw } from "#shared/jsx/jsx-runtime.ts";
import type { TableColumn } from "#shared/tables/column.ts";
import { defineTable } from "#shared/tables/definition.ts";
import type { AdminSession, Holiday } from "#shared/types.ts";
import { recordEditPanel } from "#templates/admin/admin-page.tsx";
import {
  defineAdminResourcePages,
  writableNameColumn,
} from "#templates/admin/resource-pages.tsx";
import { ActionButton, GuideFooter } from "#templates/components/actions.tsx";
import { renderTable } from "#templates/components/table.tsx";
import { getHolidayForm } from "#templates/fields/admin.ts";

/* jscpd:ignore-end */

/** Columns for the holidays table — declared once so the header order and
 *  cell order can't drift apart. */
const holidayColumns = (): TableColumn<Holiday>[] => [
  writableNameColumn(
    (holiday) => adminPath("holiday", { id: holiday.id }),
    (holiday) => holiday.name,
  ),
  {
    cell: (h) => h.start_date,
    header: t("holidays.col.start_date"),
    key: "start_date",
  },
  {
    cell: (h) => h.end_date,
    header: t("holidays.col.end_date"),
    key: "end_date",
  },
];

/** Shared holidays table used by the holiday settings page and dashboard. */
export const HolidayTable = ({
  holidays,
  scrollClass,
}: {
  holidays: Holiday[];
  scrollClass: string;
}): string =>
  String(renderTable(defineTable(holidayColumns()), holidays, { scrollClass }));

/** Holiday create/edit form values. Kept as a public export because the
 *  demo/replay harness and tests read it directly. */
export const holidayToFieldValues = (
  holiday?: Holiday,
): Record<string, string | number | null> =>
  entityToFieldValues(holiday, getHolidayForm().fields, {});

type HolidayRenderValues = FormRenderValuesFor<
  ReturnType<typeof getHolidayForm>["fields"]
>;

/** The entity page's Edit tab. Submitted values can replace the stored values
 * when a rejected POST is rendered in place. */
export const HolidayEditPanel = ({
  holiday,
  error,
  values,
}: {
  holiday: Holiday;
  error?: string;
  values?: HolidayRenderValues;
}): JSX.Element =>
  recordEditPanel("holidayEdit", t("common.save_changes"))(
    holiday.id,
    error,
    <Raw
      html={getHolidayForm().render(values ?? holidayToFieldValues(holiday))}
    />,
  );

export const getHolidayPages = (): ReturnType<
  typeof defineAdminResourcePages<Holiday>
> =>
  defineAdminResourcePages<Holiday>({
    active: adminPattern("holidays"),
    basePath: adminPattern("holidays"),
    delete: {
      confirm: (holiday) => ({
        args: {
          end: holiday.end_date,
          name: escapeHtml(holiday.name),
          start: holiday.start_date,
        },
        key: "holidays.delete.confirm",
      }),
      danger: false,
      heading: t("holidays.delete.heading"),
      label: t("holidays.delete.confirm_label"),
      name: (holiday) => holiday.name,
      prompt: (holiday) => ({
        args: { name: holiday.name },
        key: "holidays.delete.confirm_prompt",
      }),
    },
    labels: {
      addHeading: t("holidays.add.heading"),
      addSubmit: t("holidays.add.submit"),
      addTitle: t("holidays.add.title"),
      deleteButton: t("holidays.delete.submit"),
      deleteTitle: t("holidays.delete.heading"),
      listTitle: t("terms.holidays"),
    },
    list: {
      actions: (
        <ActionButton href={adminPattern("holidayNew")} icon="plus">
          {t("holidays.add_holiday")}
        </ActionButton>
      ),
      columns: holidayColumns(),
      empty: <p>{t("holidays.no_holidays")}</p>,
      guideFooter: (
        <GuideFooter href={`${adminPattern("guide")}#holidays`}>
          {t("holidays.guide_link")}
        </GuideFooter>
      ),
    },
    renderFields: () => <Raw html={getHolidayForm().render()} />,
  });

/** Admin holidays list page. */
export const adminHolidaysPage = (
  holidays: Holiday[],
  session: AdminSession,
  successMessage?: string,
): string =>
  getHolidayPages().listPage(holidays, session, undefined, successMessage);
