/**
 * Admin holiday management page templates.
 *
 * The list, new, and delete pages are generated by
 * {@link defineAdminResourcePages}. The edit form is a panel in the holiday
 * entity page. {@link HolidayTable} stays as a standalone export because the
 * dashboard renders it outside the resource list shell.
 */

/* jscpd:ignore-start */
import { t } from "#i18n";
import type { FormRenderValuesFor } from "#shared/forms/definition.ts";
import { entityToFieldValues } from "#shared/forms/values.ts";
import { escapeHtml, Raw } from "#shared/jsx/jsx-runtime.ts";
import type { AdminSession, Holiday } from "#shared/types.ts";
import { editPanel } from "#templates/admin/admin-page.tsx";
import {
  defineAdminResourcePages,
  writableNameColumn,
} from "#templates/admin/resource-pages.tsx";
import { ActionButton, GuideFooter } from "#templates/components/actions.tsx";
import {
  type DataColumn,
  dataTable,
} from "#templates/components/data-table.tsx";
import { SaveForm } from "#templates/components/save-form.tsx";
import { getHolidayForm } from "#templates/fields/admin.ts";

/* jscpd:ignore-end */

/** Columns for the holidays table — declared once so the header order and
 *  cell order can't drift apart. */
const holidayColumns = (): DataColumn<Holiday>[] => [
  writableNameColumn(
    (holiday) => `/admin/holidays/${holiday.id}`,
    (holiday) => holiday.name,
  ),
  { cell: (h) => h.start_date, header: t("holidays.col.start_date") },
  { cell: (h) => h.end_date, header: t("holidays.col.end_date") },
];

/** Shared holidays table used by the holiday settings page and dashboard. */
export const HolidayTable = ({
  holidays,
  scrollClass,
}: {
  holidays: Holiday[];
  scrollClass: string;
}): string => String(dataTable(holidayColumns())(holidays, { scrollClass }));

/** Holiday create/edit form values. Kept as a public export because the
 *  demo/replay harness and tests read it directly. */
export const holidayToFieldValues = (
  holiday?: Holiday,
): Record<string, string | number | null> =>
  entityToFieldValues(holiday, getHolidayForm().fields, {});

type HolidayRenderValues = FormRenderValuesFor<
  ReturnType<typeof getHolidayForm>["fields"]
>;

/** The entity page's Edit tab. Submitted values can replace the stored values
 * when a rejected POST is rendered in place. */
export const HolidayEditPanel = ({
  holiday,
  error,
  values,
}: {
  holiday: Holiday;
  error?: string;
  values?: HolidayRenderValues;
}): JSX.Element =>
  editPanel(error)(
    <SaveForm
      action={`/admin/holidays/${holiday.id}/edit`}
      submitLabel={t("common.save_changes")}
    >
      <Raw
        html={getHolidayForm().render(values ?? holidayToFieldValues(holiday))}
      />
    </SaveForm>,
  );

export const getHolidayPages = (): ReturnType<
  typeof defineAdminResourcePages<Holiday>
> =>
  defineAdminResourcePages<Holiday>({
    active: "/admin/holidays",
    basePath: "/admin/holidays",
    delete: {
      confirm: (holiday) => ({
        args: {
          end: holiday.end_date,
          name: escapeHtml(holiday.name),
          start: holiday.start_date,
        },
        key: "holidays.delete.confirm",
      }),
      danger: false,
      heading: t("holidays.delete.heading"),
      label: t("holidays.delete.confirm_label"),
      name: (holiday) => holiday.name,
      prompt: (holiday) => ({
        args: { name: holiday.name },
        key: "holidays.delete.confirm_prompt",
      }),
    },
    labels: {
      addHeading: t("holidays.add.heading"),
      addSubmit: t("holidays.add.submit"),
      addTitle: t("holidays.add.title"),
      deleteButton: t("holidays.delete.submit"),
      deleteLabel: t("holidays.delete.confirm_label"),
      deleteTitle: t("holidays.delete.heading"),
      listTitle: t("terms.holidays"),
    },
    list: {
      actions: (
        <ActionButton href="/admin/holidays/new" icon="plus">
          {t("holidays.add_holiday")}
        </ActionButton>
      ),
      columns: holidayColumns(),
      empty: <p>{t("holidays.no_holidays")}</p>,
      guideFooter: (
        <GuideFooter href="/admin/guide#holidays">
          {t("holidays.guide_link")}
        </GuideFooter>
      ),
    },
    renderFields: () => <Raw html={getHolidayForm().render()} />,
  });

/** Admin holidays list page. */
export const adminHolidaysPage = (
  holidays: Holiday[],
  session: AdminSession,
  successMessage?: string,
): string =>
  getHolidayPages().listPage(holidays, session, undefined, successMessage);
