/**
 * Admin templates for managing attendee statuses (owner-only settings page).
 *
 * The list, new, and delete pages are generated by
 * {@link defineAdminResourcePages}. The edit form is a panel in the attendee
 * status entity page. The shared fields are hand-rolled because their
 * reservation amount depends on a checkbox.
 */

/* jscpd:ignore-start */
import { t } from "#i18n";
import type { AttendeeStatus } from "#shared/db/attendee-statuses.ts";
import type { FormParams } from "#shared/form-data.ts";
import { RESERVATION_AMOUNT_HINT } from "#shared/reservation-amount.ts";
import type { TableColumn } from "#shared/tables/column.ts";
import { editPanel } from "#templates/admin/admin-page.tsx";
import {
  defineAdminResourcePages,
  writableNameColumn,
} from "#templates/admin/resource-pages.tsx";
import { SettingsCheckbox } from "#templates/admin/settings/settings-checkbox.tsx";
import { ActionButton, GuideFooter } from "#templates/components/actions.tsx";
import { Badge } from "#templates/components/badge.tsx";
import { ProseIntro } from "#templates/components/prose-heading.tsx";
import { SaveForm } from "#templates/components/save-form.tsx";
import { translatedTableHeader } from "#templates/components/translated-table-column.ts";

/* jscpd:ignore-end */

const LIST_PATH = "/admin/settings/statuses";

/** Render one row's flag badges. */
const statusBadges = (s: AttendeeStatus): JSX.Element => (
  <>
    {s.is_public_default && <Badge>{t("statuses.badge_public_default")}</Badge>}
    {s.is_paid_default && <Badge>{t("statuses.badge_paid")}</Badge>}
    {s.is_reservation && (
      <Badge>
        {t("statuses.badge_reservation", { amount: s.reservation_amount })}
      </Badge>
    )}
  </>
);

/** The attendee-status data columns; ordering controls are added by the shared
 * table renderer. */
const statusColumns: TableColumn<AttendeeStatus>[] = [
  writableNameColumn(
    (s) => `${LIST_PATH}/${s.id}`,
    (s) => s.name,
  ),
  {
    cell: (s) => statusBadges(s),
    header: translatedTableHeader("statuses.flags_header"),
    key: "flags",
  },
];

/** One named checkbox for a status flag. */
const checkbox = (
  name: string,
  label: string,
  checked: boolean,
): JSX.Element => (
  <SettingsCheckbox
    checked={checked}
    label={label}
    labelClass="checkbox"
    name={name}
  />
);

/** Shared create/edit fields. Rejected edits pass their submitted values so
 * the operator can fix one field without entering the others again. */
const renderStatusFields = (
  status: AttendeeStatus | undefined,
  values?: FormParams,
): JSX.Element => (
  <>
    <label>
      {t("common.name")}
      <input
        name="name"
        required
        type="text"
        value={
          values === undefined
            ? (status?.name ?? "")
            : (values.get("name") ?? "")
        }
      />
    </label>
    <fieldset class="checkboxes">
      {checkbox(
        "is_reservation",
        t("statuses.form_reservation_checkbox"),
        values?.has("is_reservation") ?? status?.is_reservation ?? false,
      )}
      {checkbox(
        "is_public_default",
        t("statuses.form_public_default_checkbox"),
        values?.has("is_public_default") ?? status?.is_public_default ?? false,
      )}
      {checkbox(
        "is_paid_default",
        t("statuses.form_paid_default_checkbox"),
        values?.has("is_paid_default") ?? status?.is_paid_default ?? false,
      )}
    </fieldset>
    <label>
      {t("statuses.form_reservation_amount_label")}
      <input
        name="reservation_amount"
        type="text"
        value={
          values?.get("reservation_amount") ?? status?.reservation_amount ?? "0"
        }
      />
      <small>
        {RESERVATION_AMOUNT_HINT}
        {t("statuses.form_reservation_amount_hint")}
      </small>
    </label>
  </>
);

/** The entity page's Edit tab, including rejected submitted values. */
export const AttendeeStatusEditPanel = ({
  status,
  error,
  values,
}: {
  status: AttendeeStatus;
  error?: string;
  values?: FormParams;
}): JSX.Element =>
  editPanel(error)(
    <SaveForm
      action={`${LIST_PATH}/${status.id}/edit`}
      submitLabel={t("statuses.form_save_button")}
    >
      {renderStatusFields(status, values)}
    </SaveForm>,
  );

const deleteChildren = (status: AttendeeStatus): JSX.Element => (
  <p>{t("statuses.delete_confirm", { name: status.name })}</p>
);

export const statusPages = defineAdminResourcePages<AttendeeStatus>({
  active: LIST_PATH,
  basePath: LIST_PATH,
  delete: {
    children: deleteChildren,
    danger: false,
    heading: t("statuses.delete_title"),
    label: t("common.name"),
    name: (status) => status.name,
  },
  labels: {
    addHeading: t("statuses.form_title_add"),
    addSubmit: t("statuses.form_create_button"),
    addTitle: t("statuses.form_title_add"),
    deleteButton: t("statuses.delete_button"),
    deleteTitle: t("statuses.delete_title"),
    listTitle: t("statuses.attendee_statuses_page_title"),
  },
  list: {
    actions: (
      <ActionButton href={`${LIST_PATH}/new`} icon="plus">
        {t("statuses.add_status_button")}
      </ActionButton>
    ),
    columns: statusColumns,
    guideFooter: (
      <GuideFooter href="/admin/guide#attendee-statuses">
        {t("statuses.guide_link")}
      </GuideFooter>
    ),
    intro: <ProseIntro html={t("statuses.attendee_statuses_description")} />,
    reorder: {
      action: (status) => (direction) =>
        `${LIST_PATH}/${status.id}/move-${direction}`,
      header: translatedTableHeader("statuses.order_header"),
      titles: {
        down: t("statuses.move_down_title"),
        up: t("statuses.move_up_title"),
      },
    },
  },
  renderFields: renderStatusFields,
});
