/**
 * Admin templates for managing attendee statuses (owner-only settings page).
 *
 * The list, new, and delete pages are generated by
 * {@link defineAdminResourcePages}. The edit form is a panel in the attendee
 * status entity page. The shared fields are hand-rolled because their
 * reservation amount depends on a checkbox.
 */

import type { AttendeeStatus } from "#db/attendee-statuses.ts";
/* jscpd:ignore-start */
import { t } from "#i18n";
import { adminPath, adminPattern } from "#shared/admin-surface.ts";
import type { FormParams } from "#shared/form-data.ts";
import { RESERVATION_AMOUNT_HINT } from "#shared/reservation-amount.ts";
import type { TableColumn } from "#shared/tables/column.ts";
import { recordEditPanel } from "#templates/admin/admin-page.tsx";
import { ConfirmPage } from "#templates/admin/confirm-page.tsx";
import {
  defineAdminResourcePages,
  writableNameColumn,
} from "#templates/admin/resource-pages.tsx";
import { SettingsCheckbox } from "#templates/admin/settings/settings-checkbox.tsx";
import { ActionButton, GuideFooter } from "#templates/components/actions.tsx";
import { Badge } from "#templates/components/badge.tsx";
import { ProseIntro } from "#templates/components/prose-heading.tsx";
import {
  translatedTableColumn,
  translatedTableHeader,
} from "#templates/components/translated-table-column.ts";
import type { AdminSession } from "#types";

/* jscpd:ignore-end */

const LIST_PATH = adminPattern("statuses");

/** Render one row's flag badges. */
const statusBadges = (s: AttendeeStatus): JSX.Element => (
  <>
    {s.is_public_default && <Badge>{t("statuses.badge_public_default")}</Badge>}
    {s.is_paid_default && <Badge>{t("statuses.badge_paid")}</Badge>}
    {s.is_reservation && (
      <Badge>
        {t("statuses.badge_reservation", { amount: s.reservation_amount })}
      </Badge>
    )}
  </>
);

/** The attendee-status data columns; ordering controls are added by the shared
 * table renderer. */
const statusColumns: TableColumn<AttendeeStatus>[] = [
  writableNameColumn(
    (s) => adminPath("status", { id: s.id }),
    (s) => s.name,
  ),
  translatedTableColumn("flags", "statuses.flags_header", (s) =>
    statusBadges(s),
  ),
];

/** One named checkbox for a status flag. The either/or pair declares its
 *  counterpart and the refusal that explains the boundary, so the browser can
 *  disable the counterpart while this one holds. */
const checkbox = (
  name: string,
  label: string,
  checked: boolean,
  exclusive?: { other: string; why: string },
): JSX.Element => (
  <SettingsCheckbox
    checked={checked}
    label={label}
    labelClass="checkbox"
    name={name}
    {...(exclusive === undefined ? {} : { exclusive })}
  />
);

/** Shared create/edit fields. Rejected edits pass their submitted values so
 * the operator can fix one field without entering the others again. The
 * paid-default and reservation checkboxes declare their either/or pair, so
 * the browser disables the counterpart and shows why; the save keeps the
 * same refusal as its authority. */
const renderStatusFields = (
  status: AttendeeStatus | undefined,
  values?: FormParams,
): JSX.Element => (
  <>
    <label>
      {t("common.name")}
      <input
        name="name"
        required
        type="text"
        value={
          values === undefined
            ? (status?.name ?? "")
            : (values.get("name") ?? "")
        }
      />
    </label>
    <fieldset class="checkboxes">
      {checkbox(
        "is_reservation",
        t("statuses.form_reservation_checkbox"),
        values?.has("is_reservation") ?? status?.is_reservation ?? false,
        {
          other: "is_paid_default",
          why: t("statuses.error_paid_default_reservation"),
        },
      )}
      {checkbox(
        "is_public_default",
        t("statuses.form_public_default_checkbox"),
        values?.has("is_public_default") ?? status?.is_public_default ?? false,
      )}
      {checkbox(
        "is_paid_default",
        t("statuses.form_paid_default_checkbox"),
        values?.has("is_paid_default") ?? status?.is_paid_default ?? false,
        {
          other: "is_reservation",
          why: t("statuses.error_paid_default_reservation"),
        },
      )}
    </fieldset>
    <label>
      {t("statuses.form_reservation_amount_label")}
      <input
        name="reservation_amount"
        type="text"
        value={
          values?.get("reservation_amount") ?? status?.reservation_amount ?? "0"
        }
      />
      <small>
        {RESERVATION_AMOUNT_HINT}
        {t("statuses.form_reservation_amount_hint")}
      </small>
    </label>
  </>
);

/** The labels the two delete pages share — the bespoke reassign page and the
 *  stock one the CRUD factory is built with. One vocabulary, both readers. */
const DELETE_PAGE_LABELS = {
  danger: false,
  heading: t("statuses.delete_title"),
  label: t("common.name"),
  title: t("statuses.delete_title"),
} as const;

/** The status delete page: the usual type-the-name confirmation, plus — when
 *  attendees hold this status — the count, a warning, and a required picker
 *  of the statuses they can move to. The picker posts `reassign_status_id`,
 *  which the delete command reads inside its transaction. */
export const retireStatusDeletePage = (
  status: AttendeeStatus,
  held: number,
  others: readonly AttendeeStatus[],
  session: AdminSession,
  error?: string,
): string => {
  const occupied = held > 0;
  return ConfirmPage({
    action: `/admin/settings/statuses/${status.id}/delete`,
    active: LIST_PATH,
    buttonText: t("statuses.delete_button"),
    confirm: {
      args: { name: status.name },
      key: "statuses.delete_confirm",
    },
    ...DELETE_PAGE_LABELS,
    name: status.name,
    session,
    ...(occupied
      ? {
          children: (
            <label>
              {t("statuses.delete_reassign_label")}
              <select name="reassign_status_id" required>
                <option selected value="">
                  {t("statuses.delete_reassign_prompt")}
                </option>
                {others.map((other) => (
                  <option value={String(other.id)}>{other.name}</option>
                ))}
              </select>
            </label>
          ),
          prompt: {
            args: { count: held },
            key: "statuses.delete_in_use",
          },
          warning: <p>{t("statuses.delete_reassign_warning")}</p>,
        }
      : {}),
    ...(error === undefined ? {} : { error }),
  });
};

/** The entity page's Edit tab, including rejected submitted values. */
export const AttendeeStatusEditPanel = ({
  status,
  error,
  values,
}: {
  status: AttendeeStatus;
  error?: string;
  values?: FormParams;
}): JSX.Element =>
  recordEditPanel("statusEdit", t("statuses.form_save_button"))(
    status.id,
    error,
    renderStatusFields(status, values),
  );

const deleteChildren = (status: AttendeeStatus): JSX.Element => (
  <p>{t("statuses.delete_confirm", { name: status.name })}</p>
);

export const statusPages = defineAdminResourcePages<AttendeeStatus>({
  active: LIST_PATH,
  basePath: LIST_PATH,
  delete: {
    children: deleteChildren,
    ...DELETE_PAGE_LABELS,
    name: (status) => status.name,
  },
  labels: {
    addHeading: t("statuses.form_title_add"),
    addSubmit: t("statuses.form_create_button"),
    addTitle: t("statuses.form_title_add"),
    deleteButton: t("statuses.delete_button"),
    deleteTitle: t("statuses.delete_title"),
    listTitle: t("statuses.attendee_statuses_page_title"),
  },
  list: {
    actions: (
      <ActionButton href={adminPattern("statusNew")} icon="plus">
        {t("statuses.add_status_button")}
      </ActionButton>
    ),
    columns: statusColumns,
    guideFooter: (
      <GuideFooter href={`${adminPattern("guide")}#attendee-statuses`}>
        {t("statuses.guide_link")}
      </GuideFooter>
    ),
    intro: <ProseIntro html={t("statuses.attendee_statuses_description")} />,
    reorder: {
      action: (status) => (direction) =>
        `${LIST_PATH}/${status.id}/move-${direction}`,
      header: translatedTableHeader("statuses.order_header"),
      titles: {
        down: t("statuses.move_down_title"),
        up: t("statuses.move_up_title"),
      },
    },
  },
  renderFields: renderStatusFields,
});
