/**
 * Admin templates for managing attendee statuses (owner-only settings page).
 *
 * The list, new, edit, and delete pages are generated by
 * {@link defineAdminResourcePages}. The status form is hand-rolled (name +
 * checkbox fieldset + reservation-amount label) rather than `Field[]`-backed,
 * so it goes through the factory's `renderFields` callback; the edit page
 * adds no extra content, so `renderEditExtra` is omitted.
 */

/* jscpd:ignore-start */
import { t } from "#i18n";
import type { AttendeeStatus } from "#shared/db/attendee-statuses.ts";
import { Raw } from "#shared/jsx/jsx-runtime.ts";
import { RESERVATION_AMOUNT_HINT } from "#shared/reservation-amount.ts";
import type { AdminSession } from "#shared/types.ts";
import { defineAdminResourcePages } from "#templates/admin/resource-pages.tsx";
import { ActionButton } from "#templates/components/actions.tsx";
import type { DataColumn } from "#templates/components/data-table.tsx";
import { ReorderArrows } from "#templates/components/reorder.tsx";

/* jscpd:ignore-end */

const LIST_PATH = "/admin/settings/statuses";

/** Small inline badge for a status flag. */
const Badge = ({ label }: { label: string }): JSX.Element => (
  <span class="badge"> {label} </span>
);

/** Render one row's flag badges. */
const statusBadges = (s: AttendeeStatus): JSX.Element => (
  <>
    {s.is_public_default && (
      <Badge label={t("statuses.badge_public_default")} />
    )}
    {s.is_paid_default && <Badge label={t("statuses.badge_paid")} />}
    {s.is_reservation && (
      <Badge
        label={t("statuses.badge_reservation", {
          amount: s.reservation_amount,
        })}
      />
    )}
  </>
);

/** Move-up / move-down controls for reordering a status. */
const moveControls = (s: AttendeeStatus, i: number, count: number) => (
  <ReorderArrows
    action={(d) => `${LIST_PATH}/${s.id}/move-${d}`}
    count={count}
    index={i}
    titles={{
      down: t("statuses.move_down_title"),
      up: t("statuses.move_up_title"),
    }}
  />
);

/** Columns for the attendee-statuses table — declared once so header/cell
 *  order can't drift. The reorder column carries the move-up/move-down
 *  controls as one typed column. */
const statusColumns: DataColumn<AttendeeStatus>[] = [
  {
    cell: (s, i, rows) => moveControls(s, i, rows.length),
    class: "reorder",
    header: t("statuses.order_header"),
  },
  {
    cell: (s) => <a href={`${LIST_PATH}/${s.id}/edit`}>{s.name}</a>,
    header: t("common.name"),
  },
  { cell: (s) => statusBadges(s), header: t("statuses.flags_header") },
];

/** One named checkbox for a status flag. */
const checkbox = (
  name: string,
  label: string,
  checked: boolean,
): JSX.Element => (
  <label class="checkbox">
    <input checked={checked} name={name} type="checkbox" value="1" /> {label}
  </label>
);

/** The shared status form fields (name + flag checkboxes + reservation
 *  amount). Used by both the create and edit pages via the factory's
 *  `renderFields` callback, which receives `undefined` for create and the
 *  stored status for edit. */
const renderStatusFields = (
  status: AttendeeStatus | undefined,
): JSX.Element => (
  <>
    <label>
      {t("common.name")}
      <input name="name" required type="text" value={status?.name ?? ""} />
    </label>
    <fieldset class="checkboxes">
      {checkbox(
        "is_reservation",
        t("statuses.form_reservation_checkbox"),
        status?.is_reservation ?? false,
      )}
      {checkbox(
        "is_public_default",
        t("statuses.form_public_default_checkbox"),
        status?.is_public_default ?? false,
      )}
      {checkbox(
        "is_paid_default",
        t("statuses.form_paid_default_checkbox"),
        status?.is_paid_default ?? false,
      )}
    </fieldset>
    <label>
      {t("statuses.form_reservation_amount_label")}
      <input
        name="reservation_amount"
        type="text"
        value={status?.reservation_amount ?? "0"}
      />
      <small>
        {RESERVATION_AMOUNT_HINT}
        {t("statuses.form_reservation_amount_hint")}
      </small>
    </label>
  </>
);

const deleteChildren = (status: AttendeeStatus): JSX.Element => (
  <p>{t("statuses.delete_confirm", { name: status.name })}</p>
);

const { deletePage, editPage, listPage, newPage } =
  defineAdminResourcePages<AttendeeStatus>({
    active: "/admin/settings",
    basePath: LIST_PATH,
    delete: {
      children: deleteChildren,
      danger: false,
      heading: t("statuses.delete_title"),
      label: t("common.name"),
      name: (status) => status.name,
    },
    labels: {
      addHeading: t("statuses.form_title_add"),
      addSubmit: t("statuses.form_create_button"),
      addTitle: t("statuses.form_title_add"),
      deleteButton: t("statuses.delete_button"),
      deleteLabel: t("common.name"),
      deleteTitle: t("statuses.delete_title"),
      editHeading: t("statuses.form_title_edit"),
      editSubmit: t("statuses.form_save_button"),
      editTitle: t("statuses.form_title_edit"),
      listTitle: t("statuses.attendee_statuses_page_title"),
    },
    list: {
      actions: (
        <ActionButton href={`${LIST_PATH}/new`} icon="plus">
          {t("statuses.add_status_button")}
        </ActionButton>
      ),
      columns: statusColumns,
      intro: (
        <div class="prose">
          <h1>{t("statuses.attendee_statuses_page_title")}</h1>
          <p>
            <Raw html={t("statuses.attendee_statuses_description")} />
          </p>
        </div>
      ),
    },
    renderFields: renderStatusFields,
  });

/** List of attendee statuses with reorder, edit and delete controls. */
export const adminAttendeeStatusesPage = (
  statuses: AttendeeStatus[],
  session: AdminSession,
  error?: string,
  success?: string,
): string => listPage(statuses, session, error, success);

/** Shared new/edit form for an attendee status. Kept as a public export
 *  because the route handler renders one combined form page; the factory's
 *  separate `newPage`/`editPage` back it. */
export const adminAttendeeStatusFormPage = (
  session: AdminSession,
  opts: {
    status?: AttendeeStatus | undefined;
    error?: string | undefined;
  } = {},
): string => {
  const { status, error } = opts;
  return status === undefined
    ? newPage(session, error)
    : editPage(status, session, error);
};

/** Confirmation page for deleting an attendee status. */
export const adminAttendeeStatusDeletePage = deletePage;
