/**
 * Per-attendee operator-visible notes (the `system_notes` table).
 *
 * Two note types share one table:
 *  - `system` — auto-generated by the app (e.g. the refunded-but-stored booking
 *    warning). Encrypted with the symmetric DB_ENCRYPTION_KEY so a key-less
 *    system path (a webhook with no logged-in owner) can both write and read it
 *    back. Kept PII-free by convention.
 *  - `owner` — operator-authored. Encrypted with the owner public key, so it can
 *    be written without a session but read only with the owner private key.
 */

import { decrypt, encrypt } from "#shared/crypto/encryption.ts";
import {
  decryptWithOwnerKey,
  encryptWithOwnerKey,
} from "#shared/crypto/keys.ts";
import {
  execute,
  inPlaceholders,
  insert,
  queryAll,
} from "#shared/db/client.ts";
import { settings } from "#shared/db/settings.ts";
import { nowIso } from "#shared/now.ts";

export type SystemNoteType = "system" | "owner";

/** A stored note with its `note` field decrypted to plaintext. */
export type SystemNote = {
  id: number;
  attendee_id: number;
  type: SystemNoteType;
  note: string;
  created: string;
};

/** The raw row as stored — `note` still encrypted. */
type SystemNoteRow = Omit<SystemNote, "note"> & { note: string };

const NOTE_COLUMNS = "id, attendee_id, type, note, created";

/** Insert one already-encrypted note of the given type. */
const insertNote = async (
  attendeeId: number,
  type: SystemNoteType,
  encryptedNote: string,
): Promise<void> => {
  const { sql, args } = insert("system_notes", {
    attendee_id: attendeeId,
    created: nowIso(),
    note: encryptedNote,
    type,
  });
  await execute(sql, args);
};

/**
 * Record an auto-generated system note. The text MUST be PII-free: it is
 * encrypted with the symmetric DB key (recoverable from a DB dump + that key),
 * and exists so a system path with no owner session can write it.
 */
export const createSystemNote = async (
  attendeeId: number,
  note: string,
): Promise<void> => insertNote(attendeeId, "system", await encrypt(note));

/** Record an operator-authored note, encrypted with the owner public key. */
export const createOwnerNote = async (
  attendeeId: number,
  note: string,
): Promise<void> =>
  insertNote(
    attendeeId,
    "owner",
    await encryptWithOwnerKey(note, settings.publicKey),
  );

/** Decrypt one note by its type. We do not guard this: a failure here can only
 *  mean the data key itself is broken — in which case the attendee's own PII
 *  wouldn't decrypt and the page never renders at all — so masking it with a
 *  placeholder would only hide a system-wide failure behind an untestable
 *  branch. Let it throw. */
const decryptNote = (
  row: SystemNoteRow,
  privateKey: CryptoKey,
): Promise<string> =>
  row.type === "owner"
    ? decryptWithOwnerKey(row.note, privateKey)
    : decrypt(row.note);

/** Decrypt a batch of note rows, preserving order. */
export const decryptNotes = (
  rows: SystemNoteRow[],
  privateKey: CryptoKey,
): Promise<SystemNote[]> =>
  Promise.all(
    rows.map(async (row) => ({
      ...row,
      note: await decryptNote(row, privateKey),
    })),
  );

/**
 * The still-encrypted note rows for a set of attendees, oldest first. Cheap (no
 * key material): a caller can use it to decide whether any notes exist before
 * deriving the owner private key to decrypt them.
 */
export const getNoteRows = (attendeeIds: number[]): Promise<SystemNoteRow[]> =>
  attendeeIds.length === 0
    ? Promise.resolve([])
    : queryAll<SystemNoteRow>(
        `SELECT ${NOTE_COLUMNS} FROM system_notes WHERE attendee_id IN (${inPlaceholders(
          attendeeIds,
        )}) ORDER BY attendee_id, id`,
        attendeeIds,
      );

/** All decrypted notes for one attendee, oldest first. */
export const getNotesForAttendee = async (
  attendeeId: number,
  privateKey: CryptoKey,
): Promise<SystemNote[]> =>
  decryptNotes(await getNoteRows([attendeeId]), privateKey);

/**
 * Decrypted notes for a set of attendees, oldest first, for an attendee-list
 * view. The private key is derived lazily — only when at least one of the listed
 * attendees actually has a note — so a list with no notes never forces a key
 * unwrap. Returns [] when none have notes.
 */
export const loadNotesForAttendees = async (
  attendeeIds: number[],
  getPrivateKey: () => Promise<CryptoKey>,
): Promise<SystemNote[]> => {
  const rows = await getNoteRows(attendeeIds);
  return rows.length === 0 ? [] : decryptNotes(rows, await getPrivateKey());
};

/** Group decrypted notes by attendee id (input order preserved within a group). */
export const groupNotesByAttendee = (
  notes: SystemNote[],
): Map<number, SystemNote[]> => Map.groupBy(notes, (note) => note.attendee_id);

/**
 * Build the attendee id → display name map that {@link AttendeeNotesSummary}
 * labels each grouped note with. Accepts any attendee-shaped row, so the
 * listing and global attendee lists can both pass their decrypted rows
 * without each rebuilding the same `Map` literal at the call site.
 */
export const attendeeNameMap = (
  attendees: ReadonlyArray<{ id: number; name: string }>,
): Map<number, string> =>
  new Map(attendees.map((a) => [a.id, a.name] as const));

/** Load one decrypted note scoped to its attendee, or null when it doesn't exist. */
export const getAttendeeNote = async (
  attendeeId: number,
  noteId: number,
  privateKey: CryptoKey,
): Promise<SystemNote | null> => {
  const rows = await queryAll<SystemNoteRow>(
    `SELECT ${NOTE_COLUMNS} FROM system_notes WHERE id = ? AND attendee_id = ?`,
    [noteId, attendeeId],
  );
  if (rows.length === 0) return null;
  return { ...rows[0]!, note: await decryptNote(rows[0]!, privateKey) };
};

/** Delete one note, scoped to its attendee so a stray id can't reach another's. */
export const deleteAttendeeNote = (
  attendeeId: number,
  noteId: number,
): Promise<unknown> =>
  execute("DELETE FROM system_notes WHERE id = ? AND attendee_id = ?", [
    noteId,
    attendeeId,
  ]);
