/**
 * Per-attendee operator-visible notes (the `system_notes` table).
 *
 * Two note types share one table:
 *  - `system` — auto-generated by the app (e.g. the refunded-but-stored booking
 *    warning). Encrypted with the symmetric DB_ENCRYPTION_KEY so a key-less
 *    system path (a webhook with no logged-in owner) can both write and read it
 *    back. Kept PII-free by convention.
 *  - `owner` — operator-authored. Encrypted with the owner public key, so it can
 *    be written without a session but read only with the owner private key.
 */

import type { InValue } from "@libsql/client";
/* jscpd:ignore-start */
import { decrypt, encrypt } from "#shared/crypto/encryption.ts";
import {
  decryptWithOwnerKey,
  encryptWithOwnerKey,
} from "#shared/crypto/keys.ts";
import type {
  EnvKeyEncrypted,
  OwnerKeyEncrypted,
} from "#shared/crypto/sealed.ts";
import { ATTENDEE_KIND } from "#shared/db/attendees/kind.ts";
import {
  execute,
  inPlaceholders,
  insert,
  queryAll,
  type TxScope,
} from "#shared/db/client.ts";
import { settings } from "#shared/db/settings.ts";
import { nowIso } from "#shared/now.ts";
/* jscpd:ignore-end */

export type SystemNoteType = "system" | "owner";

/** A stored note with its `note` field decrypted to plaintext. */
export type SystemNote = {
  id: number;
  attendee_id: number;
  type: SystemNoteType;
  note: string;
  created: string;
};

/** The raw row as stored — `note` still encrypted. The note's sealing scheme
 * follows its type: owner notes are owner-key ciphertext, system notes env-key
 * ciphertext, so the row is a discriminated union on `type`. */
type SystemNoteRow = Omit<SystemNote, "note" | "type"> &
  (
    | { type: "owner"; note: OwnerKeyEncrypted }
    | { type: "system"; note: EnvKeyEncrypted }
  );

const NOTE_COLUMNS = "id, attendee_id, type, note, created";

/** Insert one already-encrypted note of the given type. */
const insertNote = async (
  attendeeId: number,
  type: SystemNoteType,
  encryptedNote: OwnerKeyEncrypted | EnvKeyEncrypted,
  transaction?: TxScope,
): Promise<number> => {
  const { sql, args } = insert("system_notes", {
    attendee_id: attendeeId,
    created: nowIso(),
    note: encryptedNote,
    type,
  });
  const result = transaction
    ? await transaction.execute({ args, sql })
    : await execute(sql, args);
  return Number(result.lastInsertRowid);
};

/** Build a "record a note" function: it seals the text its own way, then stores
 *  the result under the given note type. The two note kinds differ only in how
 *  they seal, so they share this one body. */
const noteCreatorVia =
  (
    type: SystemNoteType,
    seal: (note: string) => Promise<OwnerKeyEncrypted | EnvKeyEncrypted>,
  ) =>
  async (
    attendeeId: number,
    note: string,
    transaction?: TxScope,
  ): Promise<number> =>
    insertNote(attendeeId, type, await seal(note), transaction);

/**
 * Record an auto-generated system note. The text MUST be PII-free: it is
 * encrypted with the symmetric DB key (recoverable from a DB dump + that key),
 * and exists so a system path with no owner session can write it.
 */
export const createSystemNote = noteCreatorVia("system", (note) =>
  encrypt(note),
);

/** Record an operator-authored note, encrypted with the owner public key. */
export const createOwnerNote = noteCreatorVia("owner", (note) =>
  encryptWithOwnerKey(note, settings.publicKey),
);

/** Replace one system-generated note as part of a durable payment effect. */
export const updateSystemNote = async (
  attendeeId: number,
  noteId: number,
  note: string,
  transaction: TxScope,
): Promise<void> => {
  const result = await transaction.execute({
    args: [await encrypt(note), attendeeId, noteId],
    sql: `UPDATE system_notes
             SET note = ?
           WHERE attendee_id = ? AND id = ? AND type = 'system'`,
  });
  if (result.rowsAffected !== 1) {
    throw new Error(
      `System note ${noteId} was not found for attendee ${attendeeId}`,
    );
  }
};

/** Decrypt one note by its type. We do not guard this: a failure here can only
 *  mean the data key itself is broken — in which case the attendee's own PII
 *  wouldn't decrypt and the page never renders at all — so masking it with a
 *  placeholder would only hide a system-wide failure behind an untestable
 *  branch. Let it throw. */
const decryptNote = (
  row: SystemNoteRow,
  privateKey: CryptoKey,
): Promise<string> =>
  row.type === "owner"
    ? decryptWithOwnerKey(row.note, privateKey)
    : decrypt(row.note);

/** Decrypt a batch of note rows, preserving order. */
export const decryptNotes = (
  rows: SystemNoteRow[],
  privateKey: CryptoKey,
): Promise<SystemNote[]> =>
  Promise.all(
    rows.map(async (row) => ({
      ...row,
      note: await decryptNote(row, privateKey),
    })),
  );

/** Fetch the still-encrypted note rows matching a WHERE body (no leading
 *  `WHERE`), oldest first per attendee. Shared by the by-ids and by-listing
 *  reads so the column list and ordering live in one place. */
const noteRowsWhere = (
  where: string,
  args: InValue[],
): Promise<SystemNoteRow[]> =>
  queryAll<SystemNoteRow>(
    `SELECT ${NOTE_COLUMNS} FROM system_notes WHERE ${where} ORDER BY attendee_id, id`,
    args,
  );

/**
 * The still-encrypted note rows for a set of attendees, oldest first. Cheap (no
 * key material): a caller can use it to decide whether any notes exist before
 * deriving the owner private key to decrypt them.
 */
export const getNoteRows = (attendeeIds: number[]): Promise<SystemNoteRow[]> =>
  attendeeIds.length === 0
    ? Promise.resolve([])
    : noteRowsWhere(
        `attendee_id IN (${inPlaceholders(attendeeIds)})`,
        attendeeIds,
      );

/**
 * The still-encrypted note rows for every real (`kind = 'attendee'`) attendee
 * booked onto one listing, oldest first — scoped in SQL rather than by passing
 * a per-attendee id list, so the Overview never materialises (nor binds) a row
 * per attendee just to find the handful with notes.
 */
export const getNoteRowsForListing = (
  listingId: number,
): Promise<SystemNoteRow[]> =>
  noteRowsWhere(
    `attendee_id IN (SELECT listingAttendee.attendee_id
       FROM listing_attendees AS listingAttendee
       JOIN attendees AS attendee ON attendee.id = listingAttendee.attendee_id
       WHERE listingAttendee.listing_id = ? AND attendee.kind = '${ATTENDEE_KIND}')`,
    [listingId],
  );

/** All decrypted notes for one attendee, oldest first. */
export const getNotesForAttendee = async (
  attendeeId: number,
  privateKey: CryptoKey,
): Promise<SystemNote[]> =>
  decryptNotes(await getNoteRows([attendeeId]), privateKey);

/**
 * A "load decrypted notes for <selector>" reader: fetch the still-encrypted rows
 * for a selector value, then decrypt them, deriving the owner private key lazily
 * — only when at least one note exists — so a note-free view never forces a key
 * unwrap. Curried over the row-fetcher so the attendee-list and listing-scoped
 * loaders share one body.
 */
/** A "load decrypted notes for <selector>" reader: takes the selector value and
 *  a lazy owner-private-key getter, and returns the decrypted notes. */
type NotesLoader<A> = (
  selector: A,
  getPrivateKey: () => Promise<CryptoKey>,
) => Promise<SystemNote[]>;

const notesLoaderVia =
  <A>(fetchRows: (selector: A) => Promise<SystemNoteRow[]>): NotesLoader<A> =>
  async (selector, getPrivateKey) => {
    const rows = await fetchRows(selector);
    return rows.length === 0 ? [] : decryptNotes(rows, await getPrivateKey());
  };

/**
 * Decrypted notes for a set of attendees, oldest first, for an attendee-list
 * view. Returns [] when none have notes.
 */
export const loadNotesForAttendees: NotesLoader<number[]> =
  notesLoaderVia(getNoteRows);

/**
 * Decrypted notes for every real attendee on one listing, oldest first —
 * scoped in SQL (see {@link getNoteRowsForListing}). Returns [] when none have
 * notes, so the Overview's key unwrap is skipped for a note-free listing.
 */
export const loadNotesForListing: NotesLoader<number> = notesLoaderVia(
  getNoteRowsForListing,
);

/** Group decrypted notes by attendee id (input order preserved within a group). */
export const groupNotesByAttendee = (
  notes: SystemNote[],
): Map<number, SystemNote[]> => Map.groupBy(notes, (note) => note.attendee_id);

/** Load one decrypted note scoped to its attendee, or null when it doesn't exist. */
export const getAttendeeNote = async (
  attendeeId: number,
  noteId: number,
  privateKey: CryptoKey,
): Promise<SystemNote | null> => {
  const rows = await queryAll<SystemNoteRow>(
    `SELECT ${NOTE_COLUMNS} FROM system_notes WHERE id = ? AND attendee_id = ?`,
    [noteId, attendeeId],
  );
  if (rows.length === 0) return null;
  return { ...rows[0]!, note: await decryptNote(rows[0]!, privateKey) };
};

/** Delete one note, scoped to its attendee so a stray id can't reach another's. */
export const deleteAttendeeNote = (
  attendeeId: number,
  noteId: number,
): Promise<unknown> =>
  execute("DELETE FROM system_notes WHERE id = ? AND attendee_id = ?", [
    noteId,
    attendeeId,
  ]);
