name: Clean Workflow Runs

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: igorjs/gh-actions-clean-workflow@5fa2e3a4fdd40e3e7098645a0b8df08624352e5e # v7
        with:
          runs_older_than: 7
